server:
  port: 8080
spring:
  application:
    name: agile_way
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/agile_way?useSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false

